import java.awt.BorderLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.*;

public class editarPersona extends javax.swing.JPanel {

    private JMenuBar menuBar;
    
    public editarPersona(JMenuBar menuBarInicio) {
        initComponents();
        this.menuBar = menuBarInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarPersona = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoID = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        textoCorreo = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JTextField();
        textoContraseña = new javax.swing.JLabel();
        campoAñoNac = new javax.swing.JTextField();
        campoID = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        campoContraseña = new javax.swing.JTextField();
        textoNombre = new javax.swing.JLabel();
        textoAñoNac = new javax.swing.JLabel();
        textoApellidos = new javax.swing.JLabel();
        textoID1 = new javax.swing.JLabel();
        textoID2 = new javax.swing.JLabel();
        textoID3 = new javax.swing.JLabel();
        textoID4 = new javax.swing.JLabel();
        textoID5 = new javax.swing.JLabel();
        textoID6 = new javax.swing.JLabel();

        jLabel1.setText("Editar Persona");

        buscarPersona.setText("Editar");
        buscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPersonaActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID de la persona a editar:");

        textoID.setText("ID");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        textoCorreo.setText("Correo");

        campoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidosActionPerformed(evt);
            }
        });

        textoContraseña.setText("Contraseña");

        campoAñoNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAñoNacActionPerformed(evt);
            }
        });

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        campoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCorreoActionPerformed(evt);
            }
        });

        campoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseñaActionPerformed(evt);
            }
        });

        textoNombre.setText("Nombre");

        textoAñoNac.setText("Año nacimiento");

        textoApellidos.setText("Apellidos");

        textoID1.setText("Nuevo");

        textoID2.setText("Nuevo");

        textoID3.setText("Nuevo");

        textoID4.setText("Nuevo");

        textoID5.setText("Nuevo");

        textoID6.setText("Nueva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscarPersona)
                .addGap(18, 18, 18)
                .addComponent(Volver)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoID1)
                                    .addComponent(textoID2)
                                    .addComponent(textoID3)
                                    .addComponent(textoID4)
                                    .addComponent(textoID5)
                                    .addComponent(textoID6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCorreo)
                                    .addComponent(textoContraseña)
                                    .addComponent(textoNombre)
                                    .addComponent(textoApellidos)
                                    .addComponent(textoAñoNac)
                                    .addComponent(textoID))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoAñoNac, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoID)
                            .addComponent(textoID1))
                        .addGap(24, 24, 24)
                        .addComponent(textoID2)
                        .addGap(18, 18, 18)
                        .addComponent(textoID3)
                        .addGap(26, 26, 26)
                        .addComponent(textoID4)
                        .addGap(18, 18, 18)
                        .addComponent(textoID5)
                        .addGap(18, 18, 18)
                        .addComponent(textoID6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(textoNombre)
                        .addGap(18, 18, 18)
                        .addComponent(textoApellidos)
                        .addGap(26, 26, 26)
                        .addComponent(textoAñoNac)
                        .addGap(18, 18, 18)
                        .addComponent(textoCorreo)
                        .addGap(18, 18, 18)
                        .addComponent(textoContraseña))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(campoAñoNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(buscarPersona))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPersonaActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        menuBar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidosActionPerformed

    private void campoAñoNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAñoNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAñoNacActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoActionPerformed

    }//GEN-LAST:event_campoCorreoActionPerformed

    private void campoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton buscarPersona;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoAñoNac;
    private javax.swing.JTextField campoContraseña;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel textoApellidos;
    private javax.swing.JLabel textoAñoNac;
    private javax.swing.JLabel textoContraseña;
    private javax.swing.JLabel textoCorreo;
    private javax.swing.JLabel textoID;
    private javax.swing.JLabel textoID1;
    private javax.swing.JLabel textoID2;
    private javax.swing.JLabel textoID3;
    private javax.swing.JLabel textoID4;
    private javax.swing.JLabel textoID5;
    private javax.swing.JLabel textoID6;
    private javax.swing.JLabel textoNombre;
    // End of variables declaration//GEN-END:variables
}
